"""add user_id to build_operation_progress

Revision ID: c15ba3adb6a4
Revises: 
Create Date: 2026-01-29 19:37:56.454582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15ba3adb6a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('build_operation_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_build_operation_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(
            "fk_build_operation_progress_user_id_users",
            "users",
            ["user_id"],
            ["id"],
        )

    # ### end Alembic commands ###



def downgrade():
    with op.batch_alter_table("build_operations") as batch_op:
        batch_op.drop_constraint(
            "fk_build_operations_assigned_machine_id_machines",
            type_="foreignkey",
        )
        batch_op.drop_index("ix_build_operations_assigned_machine_id")

    with op.batch_alter_table("build_operation_progress") as batch_op:
        batch_op.drop_constraint(
            "fk_build_operation_progress_user_id_users",
            type_="foreignkey",
        )
        batch_op.drop_index("ix_build_operation_progress_user_id")
        batch_op.drop_column("user_id")
    # ### end Alembic commands ###
